package com.tsoft.civilization.tile;

import com.tsoft.civilization.tile.terrain.AbstractTerrain;
import com.tsoft.civilization.tile.feature.AbstractFeature;
import com.tsoft.civilization.tile.feature.FeatureList;
import com.tsoft.civilization.economic.Supply;

public class TileService {

    // Don't generate events for civilization
    // They must be generated by caller
    public Supply calcSupply(AbstractTerrain tile) {
        Supply supply = tile.getBaseSupply();

        // add feature's supply
        FeatureList features = tile.getFeatures();
        if (!features.isEmpty()) {
            // start from last (i.e. on top) feature
            for (int i = features.size() - 1; i >= 0; i --) {
                AbstractFeature feature = features.get(i);

                // look for a blocking feature
                if (feature.isBlockingTileSupply()) {
                    return feature.getSupply();
                }

                supply = supply.add(feature.getSupply());
            }
        }
        return supply;
    }
}
